# Generated by Django 5.2 on 2025-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='system_state',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='settings',
            field=models.CharField(default='system_state', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='value',
            field=models.CharField(default='Log in', max_length=50),
        ),
    ]
