# Generated by Django 5.2 on 2025-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_systemsettings_system_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='settings',
            field=models.CharField(default='system_state', max_length=50, unique=True),
        ),
    ]
