# Generated by Django 5.2 on 2025-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_systemsettings_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='settings',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
