# Generated by Django 5.2 on 2025-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_systemsettings_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
